dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('tools', views.tools, name='tools'),
    path('check', views.check, name='check'),
]

harvest/urls.py
from django.urls import path

from . import views


app_name = 'harvest'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('job-<int:job_id>', views.show, name='show'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index, tools

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', index, name='home'),
    path('', include('dashboard.urls')),
    path('harvest/', include('harvest.urls'))
]

dashboard/models.py
from django.db import models


class Sentiment(models.Model):
    label = models.CharField(max_length=50)
    total = models.IntegerField(default=0)

harvest/models.py
from enum import Enum

from django.db import models


class JobStatus(Enum):
    WAITING = 'WAITING'
    PROCESS = 'PROCESS'
    DONE = 'DONE'

    @classmethod
    def choices(cls):
        return [(key.value, key.name) for key in cls]


class Account(models.Model):
    username = models.CharField(max_length=50)
    auth_token = models.CharField(max_length=100)


class Job(models.Model):
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    keyword = models.CharField(max_length=250)
    limit = models.IntegerField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    status = models.CharField(max_length=25, choices=JobStatus.choices(), default=JobStatus.WAITING.value)

    def get_status_label(self):
        return JobStatus(self.status).name.title()

harvest/forms.py
from django import forms

from .models import Job


class CreateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['account', 'keyword', 'limit', 'start_time', 'end_time']

    # account = forms.CharField()
    # keyword = forms.CharField()
    # limit = forms.IntegerField()
    # start_time = forms.DateTimeField()
    # end_time = forms.DateTimeField()

dashboard/views.py
import json
import pickle
import re

import pandas as pd
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from nltk import WordNetLemmatizer

from dashboard.models import Sentiment
from web.settings import BASE_DIR


def preprocess(textdata):
    processedText = []

    # Create Lemmatizer and Stemmer.
    word_lemm = WordNetLemmatizer()

    # Defining regex patterns.
    url_pattern = r"((http://)[^ ]*|(https://)[^ ]*|( www\.)[^ ]*)"
    user_pattern = '@[^\s]+'
    alpha_pattern = "[^a-zA-Z0-9]"
    sequence_pattern = r"(.)\1\1+"
    seq_replace_pattern = r"\1\1"

    for tweet in textdata:
        # Defining dictionary containing all emojis with their meanings.
        emojis = {':)': 'smile', ':-)': 'smile', ';d': 'wink', ':-E': 'vampire', ':(': 'sad',
                  ':-(': 'sad', ':-<': 'sad', ':P': 'raspberry', ':O': 'surprised',
                  ':-@': 'shocked', ':@': 'shocked', ':-$': 'confused', ':\\': 'annoyed',
                  ':#': 'mute', ':X': 'mute', ':^)': 'smile', ':-&': 'confused', '$_$': 'greedy',
                  '@@': 'eyeroll', ':-!': 'confused', ':-D': 'smile', ':-0': 'yell', 'O.o': 'confused',
                  '<(-_-)>': 'robot', 'd[-_-]b': 'dj', ":'-)": 'sadsmile', ';)': 'wink',
                  ';-)': 'wink', 'O:-)': 'angel', 'O*-)': 'angel', '(:-D': 'gossip', '=^.^=': 'cat'}

        ## Defining set containing all stopwords in Bahasa Indonesia.
        stopword_df = pd.read_csv(BASE_DIR / 'static/csv/stopwordbahasa.csv', header=None)
        stopwordlist = stopword_df[0].to_list()

        tweet = tweet.lower()

        # Replace all URls with 'URL'
        tweet = re.sub(url_pattern, ' URL', tweet)
        # Replace all emojis.
        for emoji in emojis.keys():
            tweet = tweet.replace(emoji, "EMOJI" + emojis[emoji])
            # Replace @USERNAME to 'USER'.
        tweet = re.sub(user_pattern, ' USER', tweet)
        # Replace all non alphabets.
        tweet = re.sub(alpha_pattern, " ", tweet)
        # Replace 3 or more consecutive letters by 2 letter.
        tweet = re.sub(sequence_pattern, seq_replace_pattern, tweet)

        tweetwords = ''
        for word in tweet.split():
            # Checking if the word is a stopword.
            # if word not in stopwordlist:
            if len(word) > 1:
                # Lemmatizing the word.
                word = word_lemm.lemmatize(word)
                tweetwords += (word + ' ')

        processedText.append(tweetwords)

    return processedText


def load_model():
    file = open(BASE_DIR / 'static/models/vectoriser-ngram-(1,2).pickle', 'rb')
    vectoriser = pickle.load(file)
    file.close()

    file = open(BASE_DIR / 'static/models/Sentiment-SVC.pickle', 'rb')
    model = pickle.load(file)
    file.close()

    return vectoriser, model


def predict(text):
    vectoriser, model = load_model()

    vector = vectoriser.transform(preprocess(text))
    sentiment = model.predict(vector)

    return sentiment.tolist()

# Create your views here.
def index(request):
    sentiment = Sentiment.objects.all()
    total_negative = sum(entry.total for entry in sentiment if entry.label == 'negative')
    total_neutral = sum(entry.total for entry in sentiment if entry.label == 'neutral')
    total_positive = sum(entry.total for entry in sentiment if entry.label == 'positive')

    return render(request, 'index.html', {
        'total_negative': total_negative,
        'total_neutral': total_neutral,
        'total_positive': total_positive
    })


def tools(request):
    return render(request, 'tools.html')


@csrf_exempt
def check(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        sentiment_label = ['Negative', 'Neutral', 'Positive']
        sentiment = predict([data['text']])[0]

        return JsonResponse({
            'result': sentiment_label[sentiment]
        })

harvest/views.py
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from web.settings import BASE_DIR
from .forms import CreateJobForm
from .models import Account, Job


# Create your views here.
def index(request):
    jobs = Job.objects.order_by('-id')

    # Pagination
    paginator = Paginator(jobs, 10)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request, 'crawler/index.html', {'paginator': paginator, 'jobs': items})


def create(request):
    if request.method == 'POST':
        form = CreateJobForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('harvest:index')
        else:
            return HttpResponse('Error Validation: ' + str(form.errors))
    else:
        accounts = Account.objects.all()
        return render(request, 'crawler/form.html', {
            'accounts': accounts
        })


def show(request, job_id):
    job = Job.objects.filter(id=job_id).first()
    if not job:
        return HttpResponse('Error: Job Not Found', status='404')

    start = int(job.start_time.timestamp())
    end = int(job.end_time.timestamp())
    output_log = BASE_DIR / f'harvest/logs/{start}_{end}.log'

    with open(output_log, 'r') as file:
        latest_content = ''

        if request.headers.get('Accept') == 'application/json':
            if job.status == 'PROCESS':
                last_position = int(request.GET.get('last_position', 0))
                file.seek(last_position)
                latest_content = file.read()
                return JsonResponse({'latest_content': latest_content, 'pos': file.tell(), 'complete': False})
            else:
                return JsonResponse({'latest_content': '', 'pos': None, 'complete': True})
        else:
            lines = file.readlines()
            for line in lines[-20:]:
                latest_content += line

            return render(request, 'crawler/show.html', {
                'job': job,
                'pos': file.tell(),
                'latest_content': latest_content,
            })

web/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def tools(request):
    return render(request, 'tools.html')

templates/crawler/form.html
{% extends "layout/base.html" %}
{% load static %}

{% block content %}
    <div class="flex flex-wrap -mx-3">
        <div class="flex-none w-full max-w-full px-3">
            <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <div class="flex justify-between items-center p-6 pb-0 mb-2 bg-white border-b-0 border-b-solid rounded-t-2xl border-b-transparent">
                    <h6>Add New Job</h6>
                </div>
                <div class="flex-auto px-0 pt-0 pb-2">
                    <div class="p-0 overflow-x-auto">
                        <form class="px-6" action="{% url 'harvest:create' %}" method="post">
                            {% csrf_token %}
                            <div class="mb-6">
                                <label for="accounts" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Twitter Account</label>
                                <select id="accounts" name="account" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                                    {% for account in accounts %}
                                        <option value="{{ account.id }}">{{ account.username }} - {{ account.auth_token }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-6">
                                <label for="keyword" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Twitter Search Keyword</label>
                                <input type="text" id="keyword" name="keyword"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       value="prabowo OR gibran OR ganjar OR mahmud OR anies OR imin OR muhaimin OR Prabowo-Gibran OR Ganjar-Mahfud OR Anies-Muhaimin"
                                       placeholder="pilpres 2024" required>
                            </div>
                            <div class="mb-6">
                                <label for="limit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Limit</label>
                                <input type="number" id="limit" name="limit"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       value="5000" required>
                            </div>
                            <div class="mb-6">
                                <label for="start_time" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Start DateTime</label>
                                <input type="text" id="start_time" name="start_time"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       required>
                            </div>
                            <div class="mb-6">
                                <label for="end_time" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">End DateTime</label>
                                <input type="text" id="end_time" name="end_time"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       required>
                            </div>
                            <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
      const flatpickr_config = {
        enableTime: true,
        defaultDate: 'today',
        maxDate: 'today',
        dateFormat: "Y-m-d H:i",
      }

      flatpickr('#start_time', flatpickr_config)
      flatpickr('#end_time', flatpickr_config)
    </script>
{% endblock %}

templates/crawler/index.html
{% extends "layout/base.html" %}
{% load static %}
{% load tz %}

{% block content %}
    <div class="flex flex-wrap -mx-3">
        <div class="flex-none w-full max-w-full px-3">
            <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <div class="flex justify-between items-center p-6 pb-0 mb-2 bg-white border-b-0 border-b-solid rounded-t-2xl border-b-transparent">
                    <h6>Crawler Job List</h6>
                    <a type="button" href="{% url 'harvest:create' %}" class="inline-block px-6 py-3 mr-3 font-bold text-center text-white uppercase align-middle transition-all rounded-lg cursor-pointer bg-gradient-to-tl from-purple-700 to-pink-500 leading-pro text-xs ease-soft-in tracking-tight-soft shadow-soft-md bg-150 bg-x-25 hover:scale-102 active:opacity-85 hover:shadow-soft-xs">
                        <i class="fas fa-plus"></i> Add <New></New>
                    </a>
                </div>
                <div class="flex-auto px-0 pt-0 pb-2">
                    <div class="p-0 overflow-x-auto">
                        <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
                            <thead class="align-bottom">
                            <tr>
                                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">
                                    Account
                                </th>
                                <th class="px-6 py-3 pl-2 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">
                                    DateTime
                                </th>
                                <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">
                                    Status
                                </th>
                                <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400 opacity-70"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}
                                <tr>
                                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                                        {{ job.account.username }}
                                    </td>
                                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                                        {% localtime on %}
                                            {{ job.start_time }} - {{ job.end_time }}
                                        {% endlocaltime %}
                                    </td>
                                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                                        {% if job.status == 'WAITING' %}
                                            <span class="bg-gradient-to-tl from-slate-600 to-slate-300 px-2.5 text-xs rounded-1.8 py-1.4 inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white">WAITING</span>
                                        {% elif job.status == 'PROCESS' %}
                                            <span class="bg-gradient-to-tl from-blue-600 to-blue-300 px-2.5 text-xs rounded-1.8 py-1.4 inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white">PROCESS</span>
                                        {% else %}
                                            <span class="bg-gradient-to-tl from-green-600 to-green-300 px-2.5 text-xs rounded-1.8 py-1.4 inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white">DONE</span>
                                        {% endif %}
                                    </td>
                                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                                        <a href="javascript:;"
                                           class="text-xs font-semibold leading-tight text-slate-400">
                                            Edit </a>
                                        <a href="{% url 'harvest:show' job.id %}" class="text-xs font-semibold leading-tight text-slate-400">Show</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <nav class="mb-3 px-3 flex flex-row items-center justify-between">
                    <span class="current text-sm text-neutral-600">
                        Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
                    </span>
                    <ul class="list-style-none flex">
                        <li>
                            <a href="?page={{ page_obj.previous_page_number }}" class="{% if not paginator.has_previous %} 'pointer-events-none' {% endif %} pointer-events-none relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-neutral-100 dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">
                                Previous
                            </a>
                        </li>
                        {% for page in paginator.page_range %}
                            <li>
                                <a href="#" class="relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-neutral-100 dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li>
                            <a href="?page={{ paginator.next_page_number }}" class="{% if not jobs.has_next %} 'pointer-events-none' {% endif %} relative block rounded bg-transparent px-3 py-1.5 text-sm text-neutral-600 transition-all duration-300 hover:bg-neutral-100 dark:text-white dark:hover:bg-neutral-700 dark:hover:text-white">
                                Next
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

templates/crawler/show.html
{% extends "layout/base.html" %}
{% load static %}

{% block content %}
    <div class="flex flex-wrap -mx-3">
        <div class="flex-none w-full max-w-full px-3">
            <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
                <div class="flex items-center p-6 pb-0 mb-2 bg-white border-b-0 border-b-solid rounded-t-2xl border-b-transparent">
                    <h6 class="mr-3">Job Tweet {{ job.start_time }} - {{ job.end_time }}</h6>
                    {% if job.status == 'WAITING' %}
                        <span class="bg-gradient-to-tl from-slate-600 to-slate-300 px-2.5 text-xs rounded-1.8 py-1.4 inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white">WAITING</span>
                    {% elif job.status == 'PROCESS' %}
                        <span class="bg-gradient-to-tl from-blue-600 to-blue-300 px-2.5 text-xs rounded-1.8 py-1.4 inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white">PROCESS</span>
                    {% else %}
                        <span class="bg-gradient-to-tl from-green-600 to-green-300 px-2.5 text-xs rounded-1.8 py-1.4 inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white">DONE</span>
                    {% endif %}
                </div>
                <div class="flex-auto px-0 pt-0 pb-2">
                    <div class="p-0 overflow-x-auto">
                        <form class="px-6" action="{% url 'harvest:create' %}" method="post">
                            {% csrf_token %}
                            <div class="mb-6">
                                <label for="accounts" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Twitter Account</label>
                                <input id="accounts" name="account" value="{{ job.account.username }} - {{ job.account.auth_token }}" disabled
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            </div>
                            <div class="mb-6">
                                <label for="keyword" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Twitter Search Keyword</label>
                                <input type="text" id="keyword" name="keyword"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       value="{{ job.keyword }}"
                                       placeholder="pilpres 2024" disabled>
                            </div>
                            <div class="mb-6">
                                <label for="limit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Limit</label>
                                <input type="number" id="limit" name="limit"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       value="{{ job.limit }}" disabled>
                            </div>
                            <div class="mb-6">
                                <label for="start_time" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Start DateTime</label>
                                <input type="text" id="start_time" name="start_time"
                                       value="{{ job.start_time.isoformat }}" disabled
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            </div>
                            <div class="mb-6">
                                <label for="end_time" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">End DateTime</label>
                                <input type="text" id="end_time" name="end_time" value="{{ job.end_time.isoformat }}" disabled
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            </div>
                            <div class="mb-6">
                                <h6>Log:</h6>
                                <pre><code id="log-text" class="language-plaintext max-h-[500px]">{{ latest_content }}</code></pre>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/es/languages/plaintext.min.js"></script>
    <script>hljs.highlightAll();</script>
    <script>
      let currentPosition = "{{ pos }}"

      async function fetchLog() {
        const url = "{% url 'harvest:show' job.id %}" + '?last_position=' + currentPosition
        const resp = await fetch(url, {
          method: 'GET',
          mode: 'same-origin',
          cache: 'no-cache',
          headers: {
            'Accept': 'application/json'
          }
        })

        return resp.json()
      }

      function fetchL() {
        fetchLog().then(data => {
          console.log(data)
          currentPosition = data.pos

          const el = document.getElementById('log-text')
          el.append(data.latest_content)

          if (data.complete) {
            clearInterval(fetchInterval)
          }
        })
      }

      let fetchInterval = setInterval(fetchL, 1000)
    </script>
{% endblock %}